/**
 * Stub data + pure helper functions for the Staff POS app, shaped like the eventual
 * real API (plan.md Phase 5: "stub with mock-data.js-shaped data until backend
 * exists"). Logic ported from mockup/staff-pos.html + mockup/shared/app.js's
 * syncStaffOfflineQueue/submitPurchase/submitFulfillReward — same offline-queue
 * dedup + validity rules (Gap #9 from the mockup gap-fix round), reworked as pure
 * functions over React state instead of mutating a global window.MOCK object.
 * Replace with real fetches/mutations as backend endpoints come online.
 */

export interface CustomerLookup {
  personalCode: string
  name: string
  pointsBalance: number
  campaignId: string
}

export interface RedemptionLookup {
  code: string
  rewardTitle: string
  customerName: string
  customerCode: string
  pointsDeducted: number
}

export interface ActivityEntry {
  id: string
  type: 'purchase' | 'fulfill'
  text: string
  time: string
  status: 'synced' | 'queued'
}

export interface OfflineQueueItem {
  id: string
  idempotencyKey: string
  customerCampaignCodeId: string
  campaignId: string
  actionType: 'purchase' | 'fulfill_reward'
  amountToman: number
  pointsAwarded: number
  createdAt: string
}

export type SyncResultStatus = 'synced' | 'duplicate_skipped' | 'invalid_skipped'

export interface SyncResult {
  itemId: string
  idempotencyKey: string
  actionType: OfflineQueueItem['actionType']
  status: SyncResultStatus
  pointsAwarded?: number
  reason: string
}

/** Mock customer directory, keyed by personal code — mirrors mockup's customerCampaignCodes+customers join. */
export const mockCustomerDirectory: Record<string, CustomerLookup> = {
  '48291': { personalCode: '48291', name: 'سارا احمدی', pointsBalance: 190, campaignId: 'c_narvan_autumn' },
  '33812': { personalCode: '33812', name: 'رضا محمدی', pointsBalance: 90, campaignId: 'c_narvan_autumn' },
  '71934': { personalCode: '71934', name: 'مریم کریمی', pointsBalance: 40, campaignId: 'c_narvan_autumn' },
}

/** Mock redemption codes generated by customers on the Customer app — mirrors mockup's reward-details-preview. */
export const mockRedemptionDirectory: Record<string, RedemptionLookup> = {
  'RDM-84920': {
    code: 'RDM-84920',
    rewardTitle: 'یک فنجان قهوه گرم انتخابی',
    customerName: 'سارا احمدی',
    customerCode: '48291',
    pointsDeducted: 120,
  },
}

export const ACTIVE_CAMPAIGN_ID = 'c_narvan_autumn'
const DEFAULT_PURCHASE_POINTS = 60

export const initialActivities: ActivityEntry[] = [
  { id: 'a1', type: 'purchase', text: 'ثبت فاکتور ۲۴۰,۰۰۰ تومان برای کد 33812 (+۶۰ امتیاز)', time: '۱۵ دقیقه پیش', status: 'synced' },
  { id: 'a2', type: 'fulfill', text: 'تحویل پاداش ۲۰٪ تخفیف برای کد 71934 (کد RDM-19402)', time: '۳۲ دقیقه پیش', status: 'synced' },
  { id: 'a3', type: 'purchase', text: 'ثبت فاکتور ۹۵,۰۰۰ تومان برای کد 48291 (+۳۵ امتیاز)', time: '۱ ساعت پیش', status: 'synced' },
]

export function lookupCustomerByCode(code: string): CustomerLookup | null {
  return mockCustomerDirectory[code.trim()] ?? null
}

export function lookupRedemptionByCode(code: string): RedemptionLookup | null {
  return mockRedemptionDirectory[code.trim()] ?? null
}

export function formatToman(amount: number): string {
  return `${amount.toLocaleString('fa-IR')} تومان`
}

/**
 * Builds a client-generated idempotency key: customer code + timestamp + device id.
 * Mirrors mockup's `${codeInput}_${Date.now()}_staffDevA` convention — this key is
 * what lets syncOfflineQueue detect true duplicates on reconnect.
 */
export function makeIdempotencyKey(prefix: string, deviceId = 'staffDevA'): string {
  return `${prefix}_${Date.now()}_${deviceId}`
}

/**
 * GAP #9 PORT: server-side verification on sync. Processes each queued item against
 * a set of already-synced idempotency keys (dedup) and the known customer/campaign
 * directory (validity), same 3-outcome shape as the mockup's syncStaffOfflineQueue:
 *   1. duplicate_skipped — idempotency_key already present in syncedKeys
 *   2. invalid_skipped   — customer code not found, or campaign doesn't match ACTIVE_CAMPAIGN_ID
 *   3. synced            — valid + new -> commits, returns points to award
 * Returns per-item results; caller applies points/queue-clearing to React state.
 */
export function syncOfflineQueue(
  queue: OfflineQueueItem[],
  syncedKeys: Set<string>,
): { results: SyncResult[]; newlySyncedKeys: string[] } {
  const results: SyncResult[] = []
  const newlySyncedKeys: string[] = []

  for (const item of queue) {
    if (syncedKeys.has(item.idempotencyKey)) {
      results.push({
        itemId: item.id,
        idempotencyKey: item.idempotencyKey,
        actionType: item.actionType,
        status: 'duplicate_skipped',
        reason: 'سرور مرکزی قبلاً این تراکنش را ثبت کرده است (شناسه تکراری / Duplicate Idempotency Key).',
      })
      continue
    }

    const custValid = Object.values(mockCustomerDirectory).some(
      (c) => c.personalCode === item.customerCampaignCodeId || c.campaignId === item.campaignId,
    )
    const campaignValid = item.campaignId === ACTIVE_CAMPAIGN_ID

    if (!custValid || !campaignValid) {
      results.push({
        itemId: item.id,
        idempotencyKey: item.idempotencyKey,
        actionType: item.actionType,
        status: 'invalid_skipped',
        reason: 'کد کاربری نامعتبر است یا کمپین مربوطه دیگر فعال/معتبر نمی‌باشد (Invalid Code or Inactive Campaign).',
      })
      continue
    }

    newlySyncedKeys.push(item.idempotencyKey)
    results.push({
      itemId: item.id,
      idempotencyKey: item.idempotencyKey,
      actionType: item.actionType,
      status: 'synced',
      pointsAwarded: item.pointsAwarded,
      reason: 'با موفقیت راستی‌آزمایی و در سرور مرکزی ثبت شد.',
    })
  }

  return { results, newlySyncedKeys }
}

export { DEFAULT_PURCHASE_POINTS }
